exports.phrases = [
  "Lectures were clear and well-structured.",
  "Course pace was appropriate for the content.",
  "Instructor explained concepts thoroughly.",
  "Examples helped reinforce theoretical material.",
  "Could include more real-world applications.",
  "Teaching methodology was effective and engaging.",
  "Concepts were explained with good clarity.",
  "The instructor was approachable and helpful.",
  "Syllabus was covered in a systematic manner.",
  "Feedback on assignments was timely and useful.",
  "The instructor encouraged active participation.",
  "Difficult topics were broken down well.",
  "Good balance between theory and practice.",
  "The course material was up to date.",
  "The instructor maintained a good pace throughout.",
  "Questions were addressed clearly during lectures.",
  "Overall a well-organized and productive course.",
  "The instructor demonstrated strong subject knowledge.",
  "Interactive sessions made the class more engaging.",
  "Slides and notes were easy to follow.",
];
